version: "3"

services:
  api:
    container_name: api-container
    build: .
    image: login-manager-api
    restart: always
    command: yarn debugs
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"